---
title: "Bahamas Bistro Status Report"
author: "Tim Fraser"
output: 
  html_document:
    self_contained: TRUE
---
```{r setup, include = FALSE}

# Load packages
library(dplyr)
library(readr)
library(ggplot2)
library(knitr)

# Load data

# Viewable Share link
# "https://docs.google.com/spreadsheets/d/15yBf5tapFSq-n6668GQ_fa3LQNafJUtxxJdjPhbaT3c/edit?usp=sharing"

# Change share link to download link
url = "https://docs.google.com/spreadsheets/d/15yBf5tapFSq-n6668GQ_fa3LQNafJUtxxJdjPhbaT3c/export?format=csv"

# Download data
data = url %>% read_csv()
```

# 5 most recent actions

```{r table, echo = FALSE}
# Show the most recent 5 rows, but don't 'echo' the code
# Output nicely as a 'kable()' table
data %>% 
  tail(5) %>% 
  select(Timestamp, order_id, task, team, person, done, elapsed) %>%
  kable()
```


# Summary Statistics

```{r stats, echo = FALSE}
stat1 = data %>% 
  summarize(
    n_customers = length(unique(order_id )),
    n_customers_served = length(unique(order_id[done == TRUE] ))
  )

stat2 = data %>%
  filter(done == TRUE) %>%
  group_by(order_id) %>%
  summarize(total_time = sum(elapsed)) %>%
  ungroup() %>%
  summarize(avg_time_to_completion = mean(total_time))
```

- Total Customers: `r stat1$n_customers`
- Total Customers Served: `r stat1$n_customers_served`
- Average Time to Order Completion: `r stat2$avg_time_to_completion`


# Employee Performance - House Front

```{r viz, echo = FALSE}
viz1 = data %>%
  filter(team == "Front") %>%
  group_by(person) %>%
  summarize(time_avg = mean(elapsed))

ggplot() +
  geom_col(data = viz1, mapping = aes(x = person, y = time_avg)) +
  coord_flip()
```
