---
title: "Bahamas Bistro Status Report"
author: "Tim Fraser"
output: 
  html_document:
    self_contained: TRUE
---


```{r setup, include = FALSE}

# Load packages
library(dplyr)
library(readr)
library(ggplot2)
library(knitr)
# Load functions
source("functions.R")

# Load data

# Viewable Share link
# "https://docs.google.com/spreadsheets/d/15yBf5tapFSq-n6668GQ_fa3LQNafJUtxxJdjPhbaT3c/edit?usp=sharing"

data = get_data(n = 100)
```

# 5 most recent actions

```{r table, echo = FALSE}
# Show the most recent 5 rows, but don't 'echo' the code
# Output nicely as a 'kable()' table
data %>% 
  tail(5) %>% 
  select(Timestamp, order_id, task, team, person, done, elapsed) %>%
  kable()
```


# Summary Statistics

```{r stats, echo = FALSE}

stat1 = get_n(data)
stat2 = get_time_avg(data)
```

- Total Customers: `r stat1$n_customers`
- Total Customers Served: `r stat1$n_customers_served`
- Average Time to Order Completion: `r stat2$avg_time_to_completion`


# Employee Performance - House Front

```{r viz, echo = FALSE}
viz1 = get_viz_by_team(data, .team = "Front")

viz1
```
